app:
  baseUrl: https://backstage.ithings.ch

backend:
  baseUrl: https://backstage.ithings.ch
  listen:
    port:
      $env: PORT

auth:
  environment: production
  providers:
    github:
      production:
        clientId:
          $env: GITHUB_PRODUCTION_CLIENT_ID
        clientSecret:
          $env: GITHUB_PRODUCTION_CLIENT_SECRET

